name: Bundle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y zip ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build bundle
     - run: flutter build apk
     - run: cd build/flutter_assets && zip -r bundle.zip .
     - uses: actions/upload-artifact@v3
       with:
          name: flutter-bundle
          path: bundle.zip
     - name: Generate release tag
       id: generate_release_tag
       uses: amitsingh-007/next-release-tag@v4.0.0
       with:
          github_token: ${{ secrets.deploy }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'          
     -  id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.deploy }} 
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          draft: false
          prerelease: false
     -  name: Upload Bundle
        id: upload-bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.deploy }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/flutter_assets/bundle.zip
          asset_name: bundle.zip
          asset_content_type: application/zip
     -  name: Upload APK
        id: upload-apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.deploy }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: pathfinder.apk
          asset_content_type: application/vnd.android.package-archive